######################################################################
# Automatically generated by qmake (2.01a) niedz. lip 4 15:52:01 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += common.h drawview.h lista.h stos.h
SOURCES += drawview.cpp main.cpp
